version: '3.8'

services:
  ai-threat-detection:
    image: ai-threat-detection:latest
    container_name: ai-threat-detection
    volumes:
      - ./core-modules/ai-threat-detection:/app
    environment:
      - MODEL_PATH=/app/ml-models/anomaly-detection-model.pkl
      - SIGNATURE_MODEL_PATH=/app/ml-models/signature-based-model.pkl
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  compliance-management:
    image: compliance-management:latest
    container_name: compliance-management
    volumes:
      - ./core-modules/compliance-management:/app
    environment:
      - REGULATIONS_PATH=/app/regulations
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  user-management:
    image: user-management:latest
    container_name: user-management
    volumes:
      - ./core-modules/user-management:/app
    environment:
      - USER_DB_PATH=/app/user-database.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  incident-response:
    image: incident-response:latest
    container_name: incident-response
    volumes:
      - ./core-modules/incident-response:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  reporting:
    image: reporting:latest
    container_name: reporting
    volumes:
      - ./core-modules/reporting:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  logging:
    image: logging:latest
    container_name: logging
    volumes:
      - ./support-modules/logging:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  monitoring:
    image: monitoring:latest
    container_name: monitoring
    volumes:
      - ./support-modules/monitoring:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  notification:
    image: notification:latest
    container_name: notification
    volumes:
      - ./support-modules/notification:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api-integration:
    image: api-integration:latest
    container_name: api-integration
    volumes:
      - ./support-modules/api-integration:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
