apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-threat-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-threat-detection
  template:
    metadata:
      labels:
        app: ai-threat-detection
    spec:
      containers:
      - name: ai-threat-detection
        image: ai-threat-detection:latest
        ports:
        - containerPort: 5000
        env:
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: fernet-secret
              key: FERNET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ai-threat-detection-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: ai-threat-detection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compliance-management
  template:
    metadata:
      labels:
        app: compliance-management
    spec:
      containers:
      - name: compliance-management
        image: compliance-management:latest
        ports:
        - containerPort: 5001
        env:
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: fernet-secret
              key: FERNET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-management-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: compliance-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management:latest
        ports:
        - containerPort: 5002
        env:
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: fernet-secret
              key: FERNET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5002
  selector:
    app: user-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-response
spec:
  replicas: 3
  selector:
    matchLabels:
      app: incident-response
  template:
    metadata:
      labels:
        app: incident-response
    spec:
      containers:
      - name: incident-response
        image: incident-response:latest
        ports:
        - containerPort: 5003
        env:
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: fernet-secret
              key: FERNET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: incident-response-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5003
  selector:
    app: incident-response
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: reporting-service:latest
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: templates
          mountPath: /app/templates
        - name: reports
          mountPath: /app/reports
      volumes:
      - name: templates
        hostPath:
          path: /path/to/templates
      - name: reports
        hostPath:
          path: /path/to/reports
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5004
  selector:
    app: reporting-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: logging-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5005
  selector:
    app: logging-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: monitoring-agent:latest
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-agent-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5006
  selector:
    app: monitoring-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 5007
        env:
        - name: NOTIFICATION_CONFIG_PATH
          value: /app/notification_config.json
        volumeMounts:
        - name: notification-config
          mountPath: /app/notification_config.json
          subPath: notification_config.json
      volumes:
      - name: notification-config
        configMap:
          name: notification-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5007
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-integration
  template:
    metadata:
      labels:
        app: api-integration
    spec:
      containers:
      - name: api-integration
        image: api-integration:latest
        ports:
        - containerPort: 5008
        env:
        - name: API_KEY_PATH
          value: /app/api-keys.json
        volumeMounts:
        - name: api-keys
          mountPath: /app/api-keys.json
          subPath: api-keys.json
      volumes:
      - name: api-keys
        configMap:
          name: api-keys
---
apiVersion: v1
kind: Service
metadata:
  name: api-integration-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5008
  selector:
    app: api-integration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  notification_config.json: |
    {
      "email": {
        "sender": "noreply@cybersec.com",
        "smtp_server": "localhost",
        "smtp_port": 25,
        "use_tls": false,
        "smtp_username": "",
        "smtp_password": ""
      },
      "sms": {
        "account_sid": "",
        "auth_token": "",
        "twilio_number": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-keys
data:
  api-keys.json: |
    {
      "vendor1_api_key": "your_vendor1_api_key_here",
      "vendor2_api_key": "your_vendor2_api_key_here"
    }
