ai:
  model_path: "data/model.h5"
  learning_rate: 0.001
  epsilon: 0.1
  gamma: 0.9
exploit:
  exploit_dir: "data/exploits/"
  default_exploit: "default_exploit.py"
network:
  timeout: 10
  retries: 3
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
