apiVersion: apps/v1
kind: Deployment
metadata:
  name: huggingface-deployment
  labels:
    app: huggingface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huggingface
  template:
    metadata:
      labels:
        app: huggingface
    spec:
      containers:
      - name: huggingface-container
        image: huggingface/image:latest
        ports:
        - containerPort: 80
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: huggingface-secrets
              key: api-key
        - name: HUGGINGFACE_MODEL
          value: "model-name"
        - name: HUGGINGFACE_ENV
          value: "production"
